#!/bin/bash

PREURL="http://dl.fullcirclemagazine.org/issue"
LANG="en"
FORMAT="pdf"
#TODO: Specify download directory

while getopts "el:" options; do
    case $options in
        e)
            FORMAT="epub"
            ;;
        l)
            LANG=$OPTARG
            ;;
    esac
done

n=1
while [ $# -gt 0 ]; do
    if [ $n -lt $OPTIND ]; then
        let n=$n+1
        shift
    else
        break
    fi
done

if [ $# -eq 0 ]; then
    echo "Which issue? "
    read ISSUE
elif [ $# -eq 1 ]; then
    ISSUE=$1
elif [ $# -eq 2 ]; then
    #TODO: This doesn't work
    ISSUE={$1..$2}
fi

#TODO: Check for positive whole numbers
#TODO: Add 404 check
wget -c $PREURL$ISSUE"_"$LANG"."$FORMAT
